import {
  buildMetrics,
  formatFullDate,
  formatTemperature,
  formatTemperatureWithUnit,
} from '../lib/format'
import { formatAge, stalenessNotice } from '../lib/messages'
import { useLiveAge } from '../hooks/useLiveAge'
import DailyForecast from './DailyForecast'
import HourlyStrip from './HourlyStrip'
import MetricIcon from './MetricIcon'
import WeatherIcon from './WeatherIcon'

/**
 * The weather dashboard for a selected location.
 *
 * Two commitments hold throughout:
 *
 * 1. Nothing is invented. Every value here exists in the Weather-AI response.
 *    That provider returns no humidity, feels-like, pressure or visibility, so
 *    those cards do not exist rather than showing placeholders.
 * 2. Freshness is never overstated. Cached and stale readings say so in words,
 *    and stale data carries an explicit notice above the reading.
 */
export default function Dashboard({ data, onBack, onRefresh }) {
  const { location, current, hourly, daily, ai_summary: aiSummary, meta } = data

  const units = current?.units || 'metric'
  const metrics = buildMetrics(current, daily)
  const notice = stalenessNotice(meta)

  const temperature = formatTemperature(current?.temperature)
  const spokenTemperature = formatTemperatureWithUnit(current?.temperature, units)

  return (
    <div className="dashboard">
      <div className="dashboard__bar">
        <button type="button" className="linkback" onClick={onBack}>
          <ArrowLeft />
          <span>Search locations</span>
        </button>
        <Freshness meta={meta} onRefresh={onRefresh} />
      </div>

      {notice && (
        <div className="notice" role="status">
          <InfoIcon />
          <span>{notice}</span>
        </div>
      )}

      <header className="hero">
        <h1 className="hero__place">
          {location.name}
          {location.kind !== 'county' && location.county && (
            <span className="hero__county">{location.county} County</span>
          )}
        </h1>
        <p className="hero__date">{formatFullDate(current?.observed_at)}</p>
      </header>

      <section className="current" aria-label="Current conditions">
        <WeatherIcon
          group={current?.condition_group}
          intensity={current?.condition_intensity}
          isDay={current?.is_day !== false}
          temperature={current?.temperature}
          size={104}
          className="current__icon"
        />
        <div className="current__readout">
          <p className="current__temp">
            <span aria-hidden="true">{temperature ?? '—'}</span>
            {spokenTemperature && (
              <span className="visually-hidden">{spokenTemperature}</span>
            )}
          </p>
          {current?.condition && (
            <p className="current__condition">{current.condition}</p>
          )}
        </div>
      </section>

      {metrics.length > 0 && (
        <ul className="metrics" aria-label="Current measurements">
          {metrics.map((metric) => (
            <li className="metric" key={metric.key}>
              <MetricIcon name={metric.icon} />
              <span className="metric__label">{metric.label}</span>
              <span className="metric__value">
                {metric.value}
                {metric.hint && <span className="metric__hint"> {metric.hint}</span>}
              </span>
            </li>
          ))}
        </ul>
      )}

      <HourlyStrip hours={hourly} units={units} />
      <DailyForecast days={daily} units={units} />

      {/* Weather-AI returns ai_summary as null on the free plan, so this
          section simply does not render rather than showing invented prose. */}
      {aiSummary && (
        <section className="panel" aria-labelledby="insight-heading">
          <h2 className="panel__title" id="insight-heading">
            Weather insight
          </h2>
          <p className="insight">{aiSummary}</p>
          <p className="insight__source">Generated by Weather-AI</p>
        </section>
      )}
    </div>
  )
}

/**
 * One honest line about where this reading came from and how old it is.
 *
 * The age ticks while the page stays open (see useLiveAge) rather than
 * freezing at whatever the server reported when the response was built. A tab
 * left open must not keep insisting the reading is "just now".
 *
 * Once the displayed age passes the cache TTL, the data on screen is no longer
 * what the server would call fresh, so the indicator says so and offers a
 * refresh instead of quietly continuing to look current.
 *
 * A cache hit is shown as a cache hit - being open about the ordinary case is
 * what makes the stale warning credible when it appears.
 */
function Freshness({ meta, onRefresh }) {
  const liveAge = useLiveAge(meta)
  const age = formatAge(liveAge)

  const ttl = Number(meta.ttl_seconds)
  const outgrewTtl = Number.isFinite(ttl) && ttl > 0 && liveAge > ttl && !meta.is_stale

  let dotClass = 'freshness__dot'
  let text

  if (meta.is_stale) {
    dotClass += ' freshness__dot--stale'
    text = `Last updated ${age} · not current`
  } else if (outgrewTtl) {
    dotClass += ' freshness__dot--stale'
    text = `Updated ${age} · may be out of date`
  } else if (meta.is_cached) {
    dotClass += ' freshness__dot--cached'
    text = `Updated ${age} · cached`
  } else {
    // A live fetch stops being "live" the moment it stops being new; after the
    // first minute the age alone is the honest description.
    text = age === 'just now' ? 'Updated just now · live' : `Updated ${age}`
  }

  return (
    <p className="freshness" aria-live="polite">
      <span className={dotClass} aria-hidden="true" />
      <span>{text}</span>
      {outgrewTtl && onRefresh && (
        <button type="button" className="freshness__refresh" onClick={onRefresh}>
          Refresh
        </button>
      )}
    </p>
  )
}

function ArrowLeft() {
  return (
    <svg
      width="15"
      height="15"
      viewBox="0 0 16 16"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M9.5 3.5 5 8l4.5 4.5" />
    </svg>
  )
}

function InfoIcon() {
  return (
    <svg
      className="notice__icon"
      width="16"
      height="16"
      viewBox="0 0 16 16"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      aria-hidden="true"
    >
      <circle cx="8" cy="8" r="6.4" />
      <path d="M8 7.4v4" strokeLinecap="round" />
      <circle cx="8" cy="5" r="0.75" fill="currentColor" stroke="none" />
    </svg>
  )
}
