# Generated by Django 5.2.17 on 2026-08-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('county', models.CharField(db_index=True, max_length=80)),
                ('kind', models.CharField(choices=[('county', 'County'), ('town', 'Town')], max_length=16)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('prominence', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-prominence', 'name'],
                'indexes': [models.Index(fields=['name'], name='locations_l_name_0dcc82_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=64, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='locations.location')),
            ],
            options={
                'verbose_name_plural': 'location aliases',
            },
        ),
    ]
